// CloneSpec — a multi-page, persistent app shape generated by the clone
// builder. Wider than AppSpec: each page is an AppNode tree, plus models
// (localStorage CRUD scaffolds) and a tiny in-memory API surface.

import { z } from "zod";

// AppNode is purposely loose here — clone templates ship AppNode-shaped
// trees that AppRuntime already renders, but we don't want to import the
// full AppSpec circular type. Keep as `unknown` and trust client render.
const AppNode = z.unknown();

export const CloneSpec = z.object({
  id: z.string().min(1).max(80),
  name: z.string().min(1).max(80),
  inspiration: z.string().min(1).max(80),
  icon: z.string().min(1).max(40),
  branding: z.object({
    primary: z.string().regex(/^#[0-9a-f]{3,8}$/i),
    secondary: z.string().regex(/^#[0-9a-f]{3,8}$/i),
    font: z.string().min(2).max(40),
  }),
  storage: z.enum(["localStorage", "indexedDB", "hydradb", "supabase"]).default("localStorage"),
  auth: z.enum(["none", "magic-link", "oauth-google", "oauth-github", "passkey"]).default("none"),
  features: z.array(z.string()).max(20),
  models: z
    .array(
      z.object({
        name: z.string().min(1).max(40),
        fields: z
          .array(
            z.object({
              name: z.string().min(1).max(40),
              type: z.enum(["string", "number", "boolean", "date", "id", "reference", "array"]),
              refTo: z.string().optional(),
            }),
          )
          .max(20),
      }),
    )
    .max(8),
  apis: z
    .array(
      z.object({
        path: z.string().min(1).max(80),
        method: z.enum(["GET", "POST", "PUT", "DELETE"]),
      }),
    )
    .max(16),
  pages: z
    .array(
      z.object({
        id: z.string().min(1).max(40),
        path: z.string().min(1).max(80),
        title: z.string().min(1).max(80),
        layout: z.enum(["full", "sidebar", "split", "tabs", "modal"]),
        root: AppNode,
      }),
    )
    .max(6),
});

export type CloneSpec = z.infer<typeof CloneSpec>;
