// W03 · /api/codegen-app/export
// Bundles a previously-generated codegen project as either a downloadable
// zip archive or a single self-contained HTML file (UMD + Babel + Tailwind).
//
// GET  ?id=<projectId>&format=zip|html · uses in-memory store (warm lambda)
// POST ?format=zip|html  body={id?,name?,files:[{path,content}]} · inline,
//      survives cold starts and serverless instance hopping
import { NextRequest } from "next/server";
import JSZip from "jszip";
import { getProject, type CodegenProject } from "@/lib/codegenProjectStore";

export const runtime = "nodejs";

function escapeHtml(s: string): string {
  return String(s).replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] ?? c),
  );
}

function bundleToSingleHtml(p: CodegenProject): string {
  const tsxFiles = p.files.filter((f) => f.path.endsWith(".tsx"));
  const tsFiles = p.files.filter((f) => f.path.endsWith(".ts") && !f.path.endsWith(".tsx"));
  const orderedScripts = [...tsFiles, ...tsxFiles];
  const scriptBlocks = orderedScripts
    .map(
      (f) =>
        `<script type="text/babel" data-presets="env,react,typescript" data-path="${escapeHtml(f.path)}">\n${f.content}\n</script>`,
    )
    .join("\n\n");
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${escapeHtml(p.name)} — DelOS export</title>
  <script src="https://unpkg.com/react@19/umd/react.production.min.js"></script>
  <script src="https://unpkg.com/react-dom@19/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>html,body{margin:0;background:#0a0a0a;color:#e5e5e5;font-family:ui-sans-serif,system-ui;}</style>
</head>
<body>
  <div id="root"></div>
${scriptBlocks}
  <script type="text/babel" data-presets="env,react,typescript">
    try {
      const root = ReactDOM.createRoot(document.getElementById('root'));
      const PageCmp = (typeof Page !== 'undefined' && Page) || (() => React.createElement('main', { className: 'p-8' }, 'DelOS export · entry point not detected'));
      root.render(React.createElement(PageCmp));
    } catch (e) {
      document.getElementById('root').innerHTML = '<pre style="padding:24px;color:#fda4af;">' + (e && e.message) + '</pre>';
    }
  </script>
</body>
</html>`;
}

async function bundle(format: string, project: CodegenProject): Promise<Response> {
  const safeName = project.name.replace(/[^a-z0-9-]+/gi, "-") || "delos-export";
  if (format === "zip") {
    const zip = new JSZip();
    for (const f of project.files) zip.file(f.path, f.content);
    if (!project.files.some((f) => /readme/i.test(f.path))) {
      zip.file("README.md", `# ${project.name}\n\nGenerated by DelOS · ${new Date(project.createdAt).toISOString()}\n`);
    }
    const buf = await zip.generateAsync({ type: "uint8array" });
    return new Response(buf as unknown as BodyInit, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${safeName}.zip"`,
      },
    });
  }
  if (format === "html") {
    return new Response(bundleToSingleHtml(project), {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="${safeName}.html"`,
      },
    });
  }
  return Response.json({ error: "bad_format", got: format }, { status: 400 });
}

export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get("id");
  const format = (req.nextUrl.searchParams.get("format") ?? "zip").toLowerCase();
  if (!id) return Response.json({ error: "id_required" }, { status: 400 });
  const project = getProject(id);
  if (!project) {
    return Response.json(
      { error: "not_found", id, hint: "Project not in lambda cache (serverless cold-start). Use POST with inline files." },
      { status: 404 },
    );
  }
  return bundle(format, project);
}

export async function POST(req: NextRequest) {
  const format = (req.nextUrl.searchParams.get("format") ?? "zip").toLowerCase();
  type InlineProj = { id?: string; name?: string; description?: string; stack?: string; files?: Array<{ path: string; content: string; language?: string }> };
  const body = (await req.json().catch(() => ({}))) as InlineProj;
  if (!Array.isArray(body.files) || body.files.length === 0) {
    return Response.json({ error: "files_required", hint: "POST { name, files: [{path,content}] }" }, { status: 400 });
  }
  const proj: CodegenProject = {
    id: body.id ?? "inline-" + Date.now().toString(36),
    name: body.name ?? "delos-export",
    description: body.description,
    stack: body.stack,
    files: body.files,
    createdAt: Date.now(),
  };
  return bundle(format, proj);
}
