// W03 · /api/codegen-app/export
// Bundles a previously-generated codegen project as either a downloadable
// zip archive or a single self-contained HTML file (UMD + Babel + Tailwind).
//
// GET  ?id=<projectId>&format=zip|html · uses in-memory store (warm lambda)
// POST ?format=zip|html  body={id?,name?,files:[{path,content}]} · inline,
//      survives cold starts and serverless instance hopping
import { NextRequest } from "next/server";
import JSZip from "jszip";
import { getProject, type CodegenProject } from "@/lib/codegenProjectStore";
import { bundleProjectToHtml } from "@/lib/previewBundle";

export const runtime = "nodejs";

async function bundle(format: string, project: CodegenProject): Promise<Response> {
  const safeName = project.name.replace(/[^a-z0-9-]+/gi, "-") || "delos-export";
  if (format === "zip") {
    const zip = new JSZip();
    for (const f of project.files) zip.file(f.path, f.content);
    if (!project.files.some((f) => /readme/i.test(f.path))) {
      zip.file("README.md", `# ${project.name}\n\nGenerated by DelOS · ${new Date(project.createdAt).toISOString()}\n`);
    }
    const buf = await zip.generateAsync({ type: "uint8array" });
    return new Response(buf as unknown as BodyInit, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${safeName}.zip"`,
      },
    });
  }
  if (format === "html") {
    return new Response(bundleProjectToHtml(project.files, project.name), {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="${safeName}.html"`,
      },
    });
  }
  return Response.json({ error: "bad_format", got: format }, { status: 400 });
}

export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get("id");
  const format = (req.nextUrl.searchParams.get("format") ?? "zip").toLowerCase();
  if (!id) return Response.json({ error: "id_required" }, { status: 400 });
  const project = getProject(id);
  if (!project) {
    return Response.json(
      { error: "not_found", id, hint: "Project not in lambda cache (serverless cold-start). Use POST with inline files." },
      { status: 404 },
    );
  }
  return bundle(format, project);
}

export async function POST(req: NextRequest) {
  const format = (req.nextUrl.searchParams.get("format") ?? "zip").toLowerCase();
  type InlineProj = { id?: string; name?: string; description?: string; stack?: string; files?: Array<{ path: string; content: string; language?: string }> };
  const body = (await req.json().catch(() => ({}))) as InlineProj;
  if (!Array.isArray(body.files) || body.files.length === 0) {
    return Response.json({ error: "files_required", hint: "POST { name, files: [{path,content}] }" }, { status: 400 });
  }
  const proj: CodegenProject = {
    id: body.id ?? "inline-" + Date.now().toString(36),
    name: body.name ?? "delos-export",
    description: body.description,
    stack: body.stack,
    files: body.files,
    createdAt: Date.now(),
  };
  return bundle(format, proj);
}
