// W03 · /api/codegen-app/export?id=<projectId>&format=zip|html
// Bundles a previously-generated codegen project as either a downloadable
// zip archive or a single self-contained HTML file (UMD + Babel + Tailwind).
import { NextRequest } from "next/server";
import JSZip from "jszip";
import { getProject, type CodegenProject } from "@/lib/codegenProjectStore";

export const runtime = "nodejs";

function escapeHtml(s: string): string {
  return String(s).replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] ?? c),
  );
}

function bundleToSingleHtml(p: CodegenProject): string {
  // Pull every .ts and .tsx file into in-document <script type="text/babel">
  // blocks. Babel-standalone transpiles in the browser. React + ReactDOM
  // via UMD CDN. Tailwind via play CDN so utility classes render. This is
  // a best-effort offline preview — heavy bundler features (alias paths,
  // CSS imports) won't work but the headline UI renders.
  const tsxFiles = p.files.filter((f) => f.path.endsWith(".tsx"));
  const tsFiles = p.files.filter((f) => f.path.endsWith(".ts") && !f.path.endsWith(".tsx"));
  const orderedScripts = [...tsFiles, ...tsxFiles];
  const scriptBlocks = orderedScripts
    .map(
      (f) =>
        `<script type="text/babel" data-presets="env,react,typescript" data-path="${escapeHtml(f.path)}">\n${f.content}\n</script>`,
    )
    .join("\n\n");
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${escapeHtml(p.name)} — DelOS export</title>
  <script src="https://unpkg.com/react@19/umd/react.production.min.js"></script>
  <script src="https://unpkg.com/react-dom@19/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>html,body{margin:0;background:#0a0a0a;color:#e5e5e5;font-family:ui-sans-serif,system-ui;}</style>
</head>
<body>
  <div id="root"></div>
${scriptBlocks}
  <script type="text/babel" data-presets="env,react,typescript">
    try {
      const root = ReactDOM.createRoot(document.getElementById('root'));
      // Page component is the default export of app/page.tsx · Babel-standalone
      // makes top-level declarations globals, so we read Page off window when present.
      const PageCmp = (typeof Page !== 'undefined' && Page) || (() => React.createElement('main', { className: 'p-8' }, 'DelOS export · entry point not detected'));
      root.render(React.createElement(PageCmp));
    } catch (e) {
      document.getElementById('root').innerHTML = '<pre style="padding:24px;color:#fda4af;">' + (e && e.message) + '</pre>';
    }
  </script>
</body>
</html>`;
}

export async function GET(req: NextRequest) {
  const id = req.nextUrl.searchParams.get("id");
  const format = (req.nextUrl.searchParams.get("format") ?? "zip").toLowerCase();
  if (!id) return Response.json({ error: "id_required" }, { status: 400 });
  const project = getProject(id);
  if (!project) return Response.json({ error: "not_found", id }, { status: 404 });

  if (format === "zip") {
    const zip = new JSZip();
    for (const f of project.files) zip.file(f.path, f.content);
    // Include a README header
    if (!project.files.some((f) => /readme/i.test(f.path))) {
      zip.file("README.md", `# ${project.name}\n\nGenerated by DelOS · ${new Date(project.createdAt).toISOString()}\n`);
    }
    const buf = await zip.generateAsync({ type: "uint8array" });
    return new Response(buf as unknown as BodyInit, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${project.name.replace(/[^a-z0-9-]+/gi, "-")}.zip"`,
      },
    });
  }
  if (format === "html") {
    const html = bundleToSingleHtml(project);
    return new Response(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="${project.name.replace(/[^a-z0-9-]+/gi, "-")}.html"`,
      },
    });
  }
  return Response.json({ error: "bad_format", got: format }, { status: 400 });
}
